---
version: '3'
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
    
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - /data_pro:/prometheus
    restart: unless-stopped
    command: 
      - "--config.file=/etc/prometheus/prometheus.yaml"
         
  grafana:
    image: docker.io/grafana/grafana-oss:10.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped